[package]
name = "numtest"
version = "0.1.0"
authors = ["Tamas Kis"]
edition = "2021"
description = "Unit testing for numerical methods."
documentation = "https://docs.rs/numtest"
repository = "https://github.com/tamaskis/numtest"
license = "MIT OR Apache-2.0"

exclude = ["Cargo.lock", ".github/", ".vscode/"]

[dependencies]
num-traits = "0.2.18"

[dev-dependencies]
nalgebra = "0.32.5"
ndarray = "0.15.6"
